# Generated by Django 6.0.1 on 2026-01-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='background_image',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
