# Generated by Django 6.0.1 on 2026-01-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_bio_about_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='about_text',
            field=models.TextField(),
        ),
    ]
